### ISSUE TITLE
[CODESTYLE] Remove prefered collection methods cop

### ISSUE THREAD

**Issue by ixti** [httprb/http#99]
I propose to remove following rubocop config in favor of default settings.

``` yaml
# Align with the style guide.
CollectionMethods:
  PreferredMethods:
    collect: 'map'
    inject: 'reduce'
    find: 'detect'
    find_all: 'select'
```

I might have strange reason, but with existing config, you will not be able to use `Pathname#find` (although we don't use it at the moment).
